import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'

const fira = Fira_Code({ subsets: ['latin'], weight:"400" })

export const metadata: Metadata = {
	title: 'About Page',
	description: 'Generated by create next app',
}

export default function AboutLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<section>
			<p className={fira.className}>start About</p>
			{children}
			<p>End About</p>
		</section>
	)
}
